"""Contenido de la guía. Es texto original de fan: resúmenes propios, sin copiar material oficial."""

SIDES = {
    "imperio": {
        "name": "El Imperio de la Humanidad",
        "blurb": "Un imperio teocrático y militarista que defiende a la humanidad a cualquier precio, incluso el de su propia libertad.",
    },
    "caos": {
        "name": "Las fuerzas del Caos",
        "blurb": "Traidores, cultistas y demonios al servicio de los dioses de la Disformidad.",
    },
    "xenos": {
        "name": "Los xenos",
        "blurb": "Razas no humanas, cada una con su propia historia y sus propios motivos. Para el Imperio, todas son enemigas.",
    },
}

LEVELS = {
    1: "Entrada fácil",
    2: "Mejor con algo de contexto",
    3: "Para cuando ya conozcas lo básico",
}

FACTIONS = [
    # ------------------------------------------------------------------ IMPERIO
    {
        "slug": "astartes",
        "name": "Adeptus Astartes (Marines Espaciales)",
        "side": "imperio",
        "color": "#5b8bd9",
        "tagline": "Superhumanos con armadura: el puño blindado del Emperador.",
        "tone": "Épico y heroico",
        "difficulty": 1,
        "summary": [
            "Los Marines Espaciales son guerreros modificados genéticamente y entrenados desde niños, capaces de enfrentarse solos a decenas de soldados normales. El Emperador los creó a partir de la semilla genética de sus veinte hijos, los Primarcas, y los lanzó a la Gran Cruzada para reconquistar la galaxia.",
            "Tras la Herejía de Horus, Roboute Guilliman escribió el Codex Astartes, que dividió las Legiones en Capítulos de unos mil guerreros. Hoy hay Capítulos de todo tipo: los disciplinados Ultramarines, los trágicos Blood Angels, los feroces Space Wolves, los reservados Dark Angels o los fanáticos Black Templars.",
        ],
        "key_points": [
            "Son pocos, pero cada uno vale por muchos soldados corrientes.",
            "Cada Capítulo tiene su propia cultura y sus propias tradiciones.",
            "Los Primaris son una nueva generación de marines, obra de Belisarius Cawl.",
            "Guilliman regresó tras diez mil años y ahora gobierna como Lord Comandante del Imperio.",
        ],
        "characters": ["Roboute Guilliman", "Marneus Calgar", "Belisarius Cawl"],
        "reading": [
            "Horus Rising, de Dan Abnett (el inicio de la Herejía de Horus)",
            "Helsreach, de Aaron Dembski-Bowden (Templarios Negros)",
        ],
        "rivals": ["chaos-marines", "tyranids", "necrons"],
    },
    {
        "slug": "militarum",
        "name": "Astra Militarum (Guardia Imperial)",
        "side": "imperio",
        "color": "#a89253",
        "tagline": "Miles de millones de soldados humanos. Sin ellos no habría Imperio.",
        "tone": "Bélico, humano y con humor negro",
        "difficulty": 1,
        "summary": [
            "La mayor fuerza militar de la galaxia no son los superhumanos, sino la gente corriente. Cada mundo del Imperio debe aportar regimientos al Astra Militarum: infantería, tanques, artillería y hasta Titanes. Su fuerza es el número y su equipo es sencillo y fiable.",
            "Un soldado de la Guardia Imperial sabe que su vida vale poco para sus superiores. Los Comisarios se encargan de mantener la disciplina, incluso ejecutando a quien huya. Aun así, aquí están las historias más humanas de Warhammer 40.000: héroes que resisten cuando todo está perdido.",
        ],
        "key_points": [
            "Cada regimiento refleja su mundo de origen: cadianos disciplinados, catachanos de selva, valhallanos de hielo.",
            "Cadia, un mundo fortaleza, cayó durante la 13.ª Cruzada Negra y su caída cambió la galaxia.",
            "Los Comisarios mantienen la moral, a las buenas o a las malas.",
        ],
        "characters": ["Ursarkar Creed", "Ibram Gaunt", "Ciaphas Cain"],
        "reading": [
            "First and Only, de Dan Abnett (serie Gaunt's Ghosts)",
            "For the Emperor, de Sandy Mitchell (serie Ciaphas Cain, con mucho humor)",
        ],
        "rivals": ["orks", "tyranids", "necrons"],
    },
    {
        "slug": "mechanicus",
        "name": "Adeptus Mechanicus",
        "side": "imperio",
        "color": "#c4622d",
        "tagline": "Sacerdotes-ingenieros que veneran la máquina.",
        "tone": "Sombrío, tecnológico y casi religioso",
        "difficulty": 2,
        "summary": [
            "El Adeptus Mechanicus gobierna Marte y decenas de Mundos Forja: fábricas planetarias que producen buena parte de la tecnología del Imperio. Son sacerdotes-ingenieros que veneran al Omnissiah, el Dios Máquina, y consideran sagrados el conocimiento y la maquinaria.",
            "Sustituyen carne por metal para acercarse a la perfección. Mandan sobre los Skitarii (soldados aumentados), los Cibernéticos y las Legiones de Titanes, gigantes de acero. Son aliados del Imperio, pero con sus propios ritos y su propia agenda.",
        ],
        "key_points": [
            "Ven la tecnología como un misterio sagrado, no como ciencia.",
            "Cada máquina tiene un espíritu al que hay que aplacar con rituales.",
            "Su relación con el resto del Imperio es una alianza, no una obediencia ciega.",
        ],
        "characters": ["Belisarius Cawl", "Kelbor-Hal"],
        "reading": ["Mechanicum, de Graham McNeill (guerra civil en Marte durante la Herejía)"],
        "rivals": ["necrons", "chaos-marines"],
    },
    {
        "slug": "sororitas",
        "name": "Adepta Sororitas (Hermanas de Batalla)",
        "side": "imperio",
        "color": "#dba7a1",
        "tagline": "La fe convertida en armadura, llama y bólter.",
        "tone": "Fanático y devoto",
        "difficulty": 2,
        "summary": [
            "Las Hermanas de Batalla son el brazo armado de la Eclesiarquía, la religión oficial del Imperio, que adora al Emperador como un dios. Como la Eclesiarquía tiene prohibido mantener ejércitos, se creó una orden de guerreras: las Adepta Sororitas.",
            "Combaten con armadura de poder, bólters, lanzallamas y una fe absoluta. Creen que la devoción, y no solo la técnica, gana batallas, y que los milagros ocurren de verdad. Se organizan en Órdenes Militantes, como la de Nuestra Señora Mártir o la de la Rosa Sagrada.",
        ],
        "key_points": [
            "Su fe se traduce en «actos de fe» que las ayudan en combate.",
            "Persiguen a herejes, mutantes y brujos por igual.",
            "Santa Celestine, una santa viviente que vuelve de la muerte, es su figura más importante.",
        ],
        "characters": ["Santa Celestine", "Morvenn Vahl"],
        "reading": ["Faith & Fire, de James Swallow (serie Hermanas de Batalla)"],
        "rivals": ["chaos-marines", "daemons"],
    },
    {
        "slug": "custodes",
        "name": "Adeptus Custodes",
        "side": "imperio",
        "color": "#d8ac2f",
        "tagline": "Los guardianes dorados del Emperador.",
        "tone": "Solemne y misterioso",
        "difficulty": 3,
        "summary": [
            "Los Custodes son los guardianes personales del Emperador. Son muy pocos (unos diez mil), pero cada uno es más fuerte y hábil que un Marine Espacial. El Emperador los creó uno a uno, aparte del sistema genético de los Primarcas.",
            "Su deber principal es custodiar el Palacio Imperial de Terra y el Trono Dorado, donde el cuerpo moribundo del Emperador se mantiene con vida. Rara vez salen de Terra: cuando lo hacen, la situación es crítica.",
        ],
        "key_points": [
            "Portan lanzas guardianas y armaduras doradas.",
            "Su fuerza está en la calidad, no en la cantidad.",
            "Su capitán-general es Trajann Valoris.",
        ],
        "characters": ["Trajann Valoris", "Constantin Valdor"],
        "reading": ["The Emperor's Legion (Watchers of the Throne), de Chris Wraight"],
        "rivals": ["chaos-marines", "daemons"],
    },
    # -------------------------------------------------- LEGIONES LEALES (Primera Fundación)
    {
        "slug": "dark-angels",
        "name": "Ángeles Oscuros (I Legión)",
        "side": "imperio",
        "color": "#3f7d4a",
        "tagline": "Caballeros con un secreto de diez mil años.",
        "tone": "Solemne y conspirativo",
        "difficulty": 3,
        "summary": [
            "Los Ángeles Oscuros fueron la Primera Legión, liderada por el Primarca Lion El'Jonson desde el mundo boscoso de Caliban. Durante la Herejía de Horus, una parte de la Legión, liderada por Luther, se rebeló por celos hacia el Primarca: son los Caídos.",
            "Desde entonces, los Ángeles Oscuros dedican tantos recursos a cazar en secreto a los Caídos supervivientes como a defender el Imperio, y ocultan ese secreto incluso a sus propios hermanos de armas. Sus Compañías Interior guardan rituales y conocimientos que ni el resto de la Legión conoce.",
        ],
        "key_points": [
            "Su Primarca, el León, desapareció tras la Herejía y solo ha reaparecido recientemente.",
            "Cazan a los Caídos con las Compañías Interior, una organización secreta dentro de la propia Legión.",
            "A diferencia de otros marines, nunca se dividieron en Capítulos: siguen siendo una única Legión.",
        ],
        "characters": ["Lion El'Jonson", "Azrael"],
        "reading": ["Descent of Angels, de Mitchel Scanlon"],
        "rivals": ["chaos-marines", "word-bearers"],
    },
    {
        "slug": "white-scars",
        "name": "Estirpe Blanca (V Legión)",
        "side": "imperio",
        "color": "#c9c4ad",
        "tagline": "Jinetes veloces de la estepa, imposibles de atrapar.",
        "tone": "Ágil y honorable",
        "difficulty": 2,
        "summary": [
            "La Estirpe Blanca desciende culturalmente de los pueblos nómadas de las estepas de Chogoris, mundo natal de su Primarca, Jaghatai Khan. Combaten a lomos de motos y vehículos rápidos, golpeando y retirándose antes de que el enemigo pueda responder.",
            "Valoran la libertad y la velocidad por encima de la doctrina rígida, algo que a veces choca con el resto del Imperio. Durante la Herejía llegaron tarde a Terra por una encerrona tendida por Alpha Legion, y aun así ayudaron a salvar el Palacio Imperial.",
        ],
        "key_points": [
            "Combaten casi siempre montados, nunca a pie si pueden evitarlo.",
            "Su cultura bébé de las estepas de Chogoris, con clanes y juras de sangre.",
            "Jaghatai Khan es uno de los pocos Primarcas cuyo paradero actual se desconoce.",
        ],
        "characters": ["Jaghatai Khan"],
        "reading": ["Scars, de Chris Wraight"],
        "rivals": ["orks", "chaos-marines"],
    },
    {
        "slug": "space-wolves",
        "name": "Lobos Espaciales (VI Legión)",
        "side": "imperio",
        "color": "#8791a3",
        "tagline": "Guerreros-lobo del hielo, ejecutores del Emperador.",
        "tone": "Feroz y tribal",
        "difficulty": 2,
        "summary": [
            "Los Lobos Espaciales, liderados por el Primarca Leman Russ, vienen del gélido Fenris. Su cultura recuerda a la vikinga: manadas, grandes salones y una ferocidad que a otras Legiones les resulta casi bárbara, aunque esconde su propia disciplina.",
            "Fueron los ejecutores del Emperador: cuando Magnus el Rojo rompió las prohibiciones sobre la hechicería, el Emperador envió a los Lobos Espaciales a arrasar Prospero, el mundo de los Mil Hijos. Esa herida entre ambas Legiones sigue abierta diez mil años después.",
        ],
        "key_points": [
            "Se organizan en «Grandes Compañías», más parecidas a manadas que a compañías normales.",
            "Sus Corredores de la Tempestad rastrean amenazas psíquicas por toda la galaxia.",
            "Su rivalidad con los Mil Hijos, por la Quema de Prospero, sigue viva.",
        ],
        "characters": ["Leman Russ", "Ragnar Blackmane"],
        "reading": ["Prospero Burns, de Dan Abnett"],
        "rivals": ["thousand-sons", "chaos-marines"],
    },
    {
        "slug": "imperial-fists",
        "name": "Puños Imperiales (VII Legión)",
        "side": "imperio",
        "color": "#d9a72f",
        "tagline": "Los que nunca ceden una muralla.",
        "tone": "Estoico y resistente",
        "difficulty": 2,
        "summary": [
            "Los Puños Imperiales, con el Primarca Rogal Dorn a la cabeza, son maestros del asedio y la fortificación: donde otras Legiones atacan, ellos resisten. Su lema, «no cederemos», resume una doctrina construida en torno al sacrificio y la defensa hasta el final.",
            "Durante la Herejía defendieron el Palacio Imperial de Terra en el asedio final contra Horus, pagando un precio altísimo. Su rivalidad con los Guerreros de Hierro de Perturabo, antes hermanos de tácticas de asedio, se volvió personal y permanente.",
        ],
        "key_points": [
            "Expertos en fortificación: construyen tan bien como destruyen.",
            "Defendieron el Palacio Imperial de Terra hasta el final de la Herejía.",
            "Su rivalidad con los Guerreros de Hierro nace de una amistad rota entre Primarcas.",
        ],
        "characters": ["Rogal Dorn"],
        "reading": [],
        "rivals": ["iron-warriors", "chaos-marines"],
    },
    {
        "slug": "blood-angels",
        "name": "Ángeles Sangrientos (IX Legión)",
        "side": "imperio",
        "color": "#b23b3b",
        "tagline": "Nobles guerreros que cargan con una maldición.",
        "tone": "Trágico y noble",
        "difficulty": 2,
        "summary": [
            "Los Ángeles Sangrientos, liderados por el hermoso y noble Primarca Sanguinius, son considerados una de las Legiones más nobles del Imperio. Sanguinius murió a manos de Horus en el Asedio de Terra, en el mismo instante en que el Emperador derrotaba al traidor.",
            "Desde entonces, todos sus descendientes cargan con dos maldiciones genéticas: la Sed Roja, un ansia de sangre, y la Furia Negra, que empuja a algunos a revivir la muerte de su Primarca en pleno combate. Aun así, siguen siendo guerreros de honor y arte.",
        ],
        "key_points": [
            "Sanguinius murió defendiendo Terra justo antes de la derrota de Horus.",
            "La Sed Roja y la Furia Negra son maldiciones genéticas que arrastra todo su linaje.",
            "Valoran el arte y la nobleza tanto como la guerra.",
        ],
        "characters": ["Sanguinius", "Dante"],
        "reading": [],
        "rivals": ["chaos-marines", "necrons"],
    },
    {
        "slug": "iron-hands",
        "name": "Manos de Hierro (X Legión)",
        "side": "imperio",
        "color": "#9aa3ab",
        "tagline": "La carne es débil; la máquina, no.",
        "tone": "Frío y disciplinado",
        "difficulty": 3,
        "summary": [
            "Las Manos de Hierro, con Ferrus Manus como Primarca, creen que la carne es débil y que la perfección está en sustituirla por metal. Muchos de sus guerreros llevan más implantes cibernéticos que cualquier otra Legión, y ven la emoción como una debilidad a superar.",
            "Ferrus Manus murió a manos de Fulgrim, su amigo más cercano entre los Primarcas, durante la traición de Isstvan V. Desde entonces las Manos de Hierro sienten un odio frío y calculado hacia los Hijos del Emperador, a quienes nunca han perdonado.",
        ],
        "key_points": [
            "Sustituyen partes de su cuerpo por implantes cibernéticos siempre que pueden.",
            "Ferrus Manus fue asesinado por Fulgrim, antes su mejor amigo entre los Primarcas.",
            "Desconfían de la debilidad, incluida la propia.",
        ],
        "characters": ["Ferrus Manus"],
        "reading": [],
        "rivals": ["emperors-children"],
    },
    {
        "slug": "ultramarines",
        "name": "Ultramarines (XIII Legión)",
        "side": "imperio",
        "color": "#3457a6",
        "tagline": "Disciplina, deber y el Codex Astartes.",
        "tone": "Ejemplar y accesible",
        "difficulty": 1,
        "summary": [
            "Los Ultramarines, liderados por Roboute Guilliman, son la Legión más numerosa y, para muchos, la que mejor representa el ideal de Marine Espacial: disciplinada, leal y bien organizada. Guilliman escribió el Codex Astartes, el texto que reorganizó a todos los marines en Capítulos tras la Herejía.",
            "Su mundo natal, Macragge, fue atacado por los Portadores de la Palabra en la batalla de Calth, una encerrona que estuvo a punto de aniquilar a la Legión entera. Hoy, con Guilliman despierto tras diez mil años, los Ultramarines son más importantes que nunca.",
        ],
        "key_points": [
            "El Codex Astartes de Guilliman organiza a casi todos los Marines Espaciales de hoy.",
            "Sobrevivieron a una encerrona masiva de los Portadores de la Palabra en Calth.",
            "Es el punto de partida más habitual para conocer a los Marines Espaciales.",
        ],
        "characters": ["Roboute Guilliman", "Marneus Calgar"],
        "reading": ["Know No Fear, de Dan Abnett"],
        "rivals": ["word-bearers"],
    },
    {
        "slug": "salamanders",
        "name": "Salamandras (XVIII Legión)",
        "side": "imperio",
        "color": "#3f8f6a",
        "tagline": "Artesanos y protectores del pueblo llano.",
        "tone": "Cálido y protector",
        "difficulty": 2,
        "summary": [
            "Las Salamandras, con Vulkan como Primarca, se distinguen por su cercanía con la gente corriente: a diferencia de otras Legiones, no se ven como superiores a la humanidad que protegen, sino como sus guardianes. Su mundo, Nocturne, es volcánico y forjó una cultura de artesanos del metal y el fuego.",
            "Vulkan desapareció durante la Herejía y se dice que su espíritu revive en distintos guerreros a lo largo de los siglos. Las Salamandras siguen fabricando algunas de las mejores armas del Imperio, y rara vez abandonan a un mundo o a un aliado a su suerte.",
        ],
        "key_points": [
            "Se consideran protectores de la gente corriente, no sus superiores.",
            "Nocturne, su mundo natal, es un planeta volcánico de artesanos del fuego y el metal.",
            "Vulkan, su Primarca, sigue desaparecido: su leyenda dice que puede regresar.",
        ],
        "characters": ["Vulkan"],
        "reading": ["Salamander, de Nick Kyme"],
        "rivals": ["chaos-marines", "orks"],
    },
    {
        "slug": "raven-guard",
        "name": "Guardia Cuervo (XIX Legión)",
        "side": "imperio",
        "color": "#4a4f5c",
        "tagline": "Golpean desde las sombras y desaparecen.",
        "tone": "Sigiloso y sombrío",
        "difficulty": 2,
        "summary": [
            "La Guardia Cuervo, liderada por Corvus Corax, prefiere el sigilo y la infiltración al combate frontal: atacan desde la oscuridad, cumplen el objetivo y desaparecen antes de que el enemigo pueda reagruparse. Su mundo, Deliverance, fue una colonia de esclavos que Corax liberó de niño.",
            "En la traición de Isstvan V, la Alpha Legion, en la que confiaban como aliada, se volvió contra ellos: la Guardia Cuervo quedó diezmada en cuestión de minutos. Esa traición marcó para siempre su forma de hacer la guerra: nunca más confiar del todo, nunca más luchar a cara descubierta si se puede evitar.",
        ],
        "key_points": [
            "Prefieren la infiltración y el golpe rápido al combate frontal.",
            "Fueron traicionados por la Alpha Legion en Isstvan V, una herida que marcó su doctrina.",
            "Corvus Corax liberó de niño el mundo esclavo de Deliverance.",
        ],
        "characters": ["Corvus Corax"],
        "reading": [],
        "rivals": ["alpha-legion"],
    },
    # ------------------------------------------------------------------ CAOS
    {
        "slug": "chaos-marines",
        "name": "Marines Espaciales del Caos",
        "side": "caos",
        "color": "#a6753b",
        "tagline": "Traidores que juraron destruir el Imperio que ayudaron a levantar.",
        "tone": "Trágico y oscuro",
        "difficulty": 2,
        "summary": [
            "Son los legionarios que siguieron a Horus, el Primarca más poderoso, cuando se volvió contra el Emperador hace diez mil años. Desde entonces muchos viven en el Ojo del Terror, una región del espacio abierta a la Disformidad, y lanzan incursiones contra el Imperio.",
            "No todos son villanos simples: muchos creen sinceramente haber elegido el bando correcto. Unos adoran a un dios del Caos concreto; otros solo buscan poder o venganza. Abaddon el Devastador lidera a la Legión Negra y ha encabezado las Cruzadas Negras.",
        ],
        "key_points": [
            "Nueve Legiones se unieron a Horus: Hijos de Horus, Hijos del Emperador, Guerreros de Hierro, Señores de la Noche, Portadores de la Palabra, Legión Alfa, Devoradores de Mundos, Guardia de la Muerte y Mil Hijos.",
            "Muchos llevan más de diez mil años en guerra.",
            "Sirven a distintos dioses del Caos, o a ninguno.",
        ],
        "characters": ["Abaddon el Devastador", "Horus"],
        "reading": ["Talon of Horus, de Aaron Dembski-Bowden"],
        "rivals": ["astartes", "sororitas", "custodes"],
    },
    {
        "slug": "death-guard",
        "name": "Guardia de la Muerte",
        "side": "caos",
        "color": "#86963f",
        "tagline": "Portadores de la plaga, resistentes a todo lo que mata.",
        "tone": "Grotesco y macabro",
        "difficulty": 2,
        "summary": [
            "La Guardia de la Muerte fue una de las nueve Legiones traidoras. Su Primarca, Mortarion, es ahora un Príncipe Demonio que sirve a Nurgle, el dios de la enfermedad, la decadencia y la perseverancia.",
            "Sus guerreros están cubiertos de pústulas y podredumbre, pero son casi imposibles de matar. Para ellos la enfermedad es un regalo, y su avance se mide en mundos infectados.",
        ],
        "key_points": [
            "Son lentos pero extremadamente resistentes.",
            "Nurgle se ve a sí mismo como un dios generoso: de la podredumbre nace nueva vida.",
            "Sus plagas son armas tan importantes como sus bólters.",
        ],
        "characters": ["Mortarion", "Typhus"],
        "reading": ["Mortarion: The Pale King, de Dan Abnett"],
        "rivals": ["astartes", "militarum"],
    },
    {
        "slug": "thousand-sons",
        "name": "Mil Hijos",
        "side": "caos",
        "color": "#3aa0d8",
        "tagline": "Hechiceros que pagaron caro su sed de conocimiento.",
        "tone": "Trágico y arcano",
        "difficulty": 3,
        "summary": [
            "Los Mil Hijos eran una Legión famosa por sus poderes psíquicos. Su Primarca, Magnus el Rojo, quiso usar la hechicería para avisar al Emperador de la traición de Horus, pero rompió las prohibiciones del Emperador y arruinó un proyecto vital en Terra.",
            "Como castigo, los Lobos Espaciales atacaron su mundo natal, Prospero. Magnus se alió con el Caos. Más tarde, el Rito del Rubrico de Ahriman intentó curar las mutaciones de la Legión, pero convirtió a casi todos en polvo animado dentro de sus armaduras.",
        ],
        "key_points": [
            "Adoran a Tzeentch, dios del cambio, la magia y la ambición.",
            "Los Rubricae son marines de polvo; los hechiceros son sus jefes.",
            "Sus planes son complejos: planes dentro de planes.",
        ],
        "characters": ["Magnus el Rojo", "Ahriman"],
        "reading": ["A Thousand Sons, de Graham McNeill"],
        "rivals": ["space-wolves", "astartes", "custodes"],
    },
    {
        "slug": "world-eaters",
        "name": "Devoradores de Mundos",
        "side": "caos",
        "color": "#dc4a3f",
        "tagline": "Furia y sangre: la guerra como culto.",
        "tone": "Brutal",
        "difficulty": 1,
        "summary": [
            "Los Devoradores de Mundos son la Legión de Angron, un Primarca criado como esclavo gladiador. Sus guerreros recibieron implantes cerebrales llamados Clavos del Carnicero, que les provocan una rabia constante.",
            "Tras la Herejía se entregaron por completo a Khorne, dios de la guerra y la sangre. Luchan cuerpo a cuerpo con hachas y sierras, sin apenas tácticas: para ellos el combate es el fin.",
        ],
        "key_points": [
            "Kharn el Traidor es su campeón más famoso y mata a amigos y enemigos por igual.",
            "Khorne no distingue de dónde viene la sangre.",
            "Son de los más fáciles de entender: rabia y carnicería.",
        ],
        "characters": ["Angron", "Kharn el Traidor"],
        "reading": ["Betrayer, de Aaron Dembski-Bowden"],
        "rivals": ["astartes", "militarum"],
    },
    # -------------------------------------------------- LEGIONES TRAIDORAS (resto)
    {
        "slug": "emperors-children",
        "name": "Hijos del Emperador (III Legión)",
        "side": "caos",
        "color": "#8a5fc2",
        "tagline": "La búsqueda de la perfección, llevada al exceso.",
        "tone": "Decadente y perturbador",
        "difficulty": 2,
        "summary": [
            "Los Hijos del Emperador, con Fulgrim como Primarca, nacieron obsesionados con la perfección: en el combate, en el arte, en todo lo que hacían. Esa búsqueda los hizo brillantes, pero también los dejó vulnerables a la tentación de ir siempre un paso más allá.",
            "Fulgrim mató a su amigo Ferrus Manus en Isstvan V y, poco después, cayó por completo bajo la influencia de Slaanesh, dios del placer y el exceso. Hoy sus guerreros persiguen sensaciones cada vez más intensas, sin límite ni freno, con una crueldad refinada casi artística.",
        ],
        "key_points": [
            "Empezaron buscando la perfección; acabaron esclavos del exceso.",
            "Fulgrim mató a Ferrus Manus, su mejor amigo entre los Primarcas.",
            "Sirven a Slaanesh, dios del placer, el arte y el exceso sin límite.",
        ],
        "characters": ["Fulgrim"],
        "reading": ["Fulgrim, de Graham McNeill"],
        "rivals": ["iron-hands"],
    },
    {
        "slug": "iron-warriors",
        "name": "Guerreros de Hierro (IV Legión)",
        "side": "caos",
        "color": "#7d7a5a",
        "tagline": "Maestros del asedio a los que nunca se reconoció el mérito.",
        "tone": "Amargo y calculador",
        "difficulty": 2,
        "summary": [
            "Los Guerreros de Hierro, con Perturabo como Primarca, eran los mejores ingenieros de asedio de la Gran Cruzada: mientras otras Legiones se llevaban la gloria de la batalla, ellos hacían el trabajo sucio de tomar fortalezas, mundo tras mundo, sin apenas reconocimiento.",
            "Ese resentimiento acumulado durante décadas empujó a Perturabo a unirse a Horus. Tras la Herejía, su rivalidad con los Puños Imperiales de Rogal Dorn, antes su amigo más cercano, se convirtió en una de las más amargas y personales de toda la galaxia.",
        ],
        "key_points": [
            "Especialistas en asedio: derriban murallas mejor que nadie.",
            "Su rivalidad con los Puños Imperiales nace de una amistad rota entre Primarcas.",
            "Perturabo sentía que nunca se le reconoció su trabajo.",
        ],
        "characters": ["Perturabo"],
        "reading": ["Storm of Iron, de Graham McNeill"],
        "rivals": ["imperial-fists"],
    },
    {
        "slug": "night-lords",
        "name": "Señores de la Noche (VIII Legión)",
        "side": "caos",
        "color": "#3a3f6e",
        "tagline": "El terror como arma, antes incluso que la fuerza.",
        "tone": "Cruel y psicológico",
        "difficulty": 2,
        "summary": [
            "Los Señores de la Noche, liderados por Konrad Curze (el Cazador Nocturno), no luchan solo para ganar: luchan para aterrorizar. Antes de que sus tropas lleguen, ya han sembrado el miedo, y creen que un enemigo aterrado se rinde antes de que haga falta matarlo.",
            "Curze, criado en un mundo criminal sin ley, gobernaba con un terror casi tan brutal contra sus propios aliados como contra sus enemigos. No sirven a ningún dios del Caos en particular: su lealtad, si existe, es solo a sí mismos y al miedo que provocan.",
        ],
        "key_points": [
            "El terror psicológico es su arma principal, antes que la fuerza bruta.",
            "No veneran a ningún dios del Caos concreto: van por libre.",
            "Konrad Curze predijo su propia muerte con años de antelación, y no hizo nada por evitarla.",
        ],
        "characters": ["Konrad Curze"],
        "reading": ["Soul Hunter, de Aaron Dembski-Bowden"],
        "rivals": ["astartes"],
    },
    {
        "slug": "word-bearers",
        "name": "Portadores de la Palabra (XVII Legión)",
        "side": "caos",
        "color": "#6e2f2f",
        "tagline": "Los primeros en arrodillarse ante los dioses oscuros.",
        "tone": "Fanático y ceremonial",
        "difficulty": 3,
        "summary": [
            "Los Portadores de la Palabra, con Lorgar como Primarca, fueron una Legión profundamente religiosa desde el principio: querían venerar al Emperador como un dios, y el Emperador, que rechazaba esa idea, humilló a Lorgar en público por ello.",
            "Esa humillación llevó a Lorgar a buscar otros dioses a los que rendir culto: los encontró en el Caos. Fueron los primeros en jurar lealtad a los poderes oscuros, mucho antes que el resto de Legiones, y tendieron una emboscada brutal a los Ultramarines en Calth.",
        ],
        "key_points": [
            "Fueron la primera Legión en jurar lealtad al Caos, antes que ninguna otra.",
            "Tendieron una encerrona a los Ultramarines en la batalla de Calth.",
            "Su fe es genuina: no fingen devoción, la sienten de verdad.",
        ],
        "characters": ["Lorgar", "Erebus"],
        "reading": ["The First Heretic, de Aaron Dembski-Bowden"],
        "rivals": ["ultramarines"],
    },
    {
        "slug": "alpha-legion",
        "name": "Legión Alfa (XX Legión)",
        "side": "caos",
        "color": "#3f9e8f",
        "tagline": "Nadie sabe realmente de qué lado están.",
        "tone": "Enigmático y estratégico",
        "difficulty": 3,
        "summary": [
            "La Legión Alfa, liderada por los Primarcas gemelos Alpharius y Omegon, funciona como una hidra: por cada cabeza que cortas, aparecen más. Se infiltran, engañan y manipulan tanto a enemigos como a aliados, y rara vez luchan si pueden ganar con una mentira.",
            "Ni siquiera está claro por qué se unieron a Horus: algunas versiones dicen que fue una decisión calculada, no ideológica, parte de un plan mucho más largo. Traicionaron a la Guardia Cuervo en Isstvan V con una emboscada perfectamente ejecutada.",
        ],
        "key_points": [
            "Su doctrina «hidra»: infiltración y engaño antes que combate directo.",
            "Alpharius y Omegon, sus Primarcas gemelos, son casi indistinguibles entre sí.",
            "Tendieron una emboscada letal a la Guardia Cuervo en Isstvan V.",
        ],
        "characters": ["Alpharius", "Omegon"],
        "reading": ["Legion, de Dan Abnett"],
        "rivals": ["raven-guard"],
    },
    {
        "slug": "daemons",
        "name": "Demonios del Caos",
        "side": "caos",
        "color": "#7b88ee",
        "tagline": "Dioses hambrientos y sus criaturas, nacidos de la emoción.",
        "tone": "Cósmico y perturbador",
        "difficulty": 3,
        "summary": [
            "La Disformidad es una dimensión hecha de emociones. De ella surgen los cuatro Dioses del Caos: Khorne (guerra y odio), Nurgle (enfermedad y decadencia), Tzeentch (cambio y magia) y Slaanesh (placer y exceso). Los demonios son manifestaciones de esos dioses.",
            "El Imperio depende de la Disformidad para viajar, pero teme que se desborde. La Gran Grieta (Cicatrix Maledictum), abierta tras la 13.ª Cruzada Negra, dividió la galaxia y multiplicó las incursiones.",
        ],
        "key_points": [
            "Slaanesh nació del exceso de los Aeldari durante su Caída.",
            "Cuanto más intensa es una emoción, más atrae a los demonios.",
            "Cultistas, brujos y traidores humanos también sirven al Caos.",
        ],
        "characters": ["Khorne", "Nurgle", "Tzeentch", "Slaanesh"],
        "reading": [],
        "rivals": ["sororitas", "custodes", "astartes"],
    },
    # ------------------------------------------------------------------ XENOS
    {
        "slug": "aeldari",
        "name": "Aeldari (Eldar)",
        "side": "xenos",
        "color": "#2fa89a",
        "tagline": "Una civilización antigua al borde de la extinción.",
        "tone": "Trágico y elegante",
        "difficulty": 2,
        "summary": [
            "Los Aeldari dominaron la galaxia hace decenas de miles de años. Según su historia, su decadencia dio a luz a Slaanesh, el dios del exceso, en un cataclismo llamado la Caída. La mayoría murió y los supervivientes se dispersaron.",
            "Los que se salvaron viven en grandes Mundos Astronave, protegidos por el Camino: una disciplina para controlar sus emociones y no atraer a Slaanesh. Cada aeldari sigue un Camino de guerra hasta que decide cambiarlo, y sus videntes, los Farseers, ven futuros posibles y guían a su pueblo.",
        ],
        "key_points": [
            "La Telaraña (Webway) es su red de túneles secretos por la galaxia.",
            "Sus almas son el alimento de Slaanesh salvo que las protejan con Piedras Espíritu.",
            "Los Ynnari son una facción que quiere dar a los Aeldari un nuevo dios, el de la Muerte.",
        ],
        "characters": ["Eldrad Ulthran", "Yvraine"],
        "reading": ["Path of the Warrior, de Gav Thorpe"],
        "rivals": ["drukhari", "orks", "tyranids", "chaos-marines"],
    },
    {
        "slug": "drukhari",
        "name": "Drukhari (Eldar Oscuros)",
        "side": "xenos",
        "color": "#b45ad6",
        "tagline": "Torturadores inmortales que se alimentan del dolor ajeno.",
        "tone": "Cruel y decadente",
        "difficulty": 3,
        "summary": [
            "Los Drukhari son los Aeldari que no huyeron ni se disciplinaron tras la Caída. Viven en Commorragh, una ciudad gigantesca en la Telaraña, y sus almas están condenadas a ser devoradas por Slaanesh.",
            "Para retrasar ese destino, capturan a miles de seres y se alimentan de su sufrimiento. Se organizan en Kabales (guerreros), Cultos de las Brujas (gladiadores) y Covens de Haemónculos (torturadores). Asdrubael Vect gobierna Commorragh con mano de hierro.",
        ],
        "key_points": [
            "Atacan con velocidad y sorpresa, en naves ligeras.",
            "Su sociedad es un nido de intrigas y traiciones.",
            "Su crueldad es a la vez necesidad y gusto.",
        ],
        "characters": ["Asdrubael Vect", "Lelith Hesperax"],
        "reading": [],
        "rivals": ["aeldari", "astartes", "militarum"],
    },
    {
        "slug": "orks",
        "name": "Orkos",
        "side": "xenos",
        "color": "#6fb04a",
        "tagline": "Guerra por diversión, y la fe de que lo que crees ocurre.",
        "tone": "Humor negro y caos",
        "difficulty": 1,
        "summary": [
            "Los Orkos son una raza de guerreros de piel verde con un solo objetivo: pelear. Se reproducen esparciendo esporas y su cultura se basa en la violencia; quien es más fuerte manda. Lo que para otras razas sería caos, para ellos es orden.",
            "Cuando se reúnen en gran número generan el Waaagh!, un campo psíquico que hace que sus máquinas, absurdas y ruidosas, funcionen mejor de lo que deberían. Bajo señores de la guerra como Ghazghkull Thraka, una invasión orka puede arrasar un mundo.",
        ],
        "key_points": [
            "Los clanes marcan estilos: Goffs (fuerza bruta), Evil Sunz (velocidad), Bad Moons (riqueza), Blood Axes (tácticas) y Deathskulls (saqueo).",
            "Los Weirdboyz canalizan la energía del Waaagh!.",
            "La galaxia entera es su campo de juego.",
        ],
        "characters": ["Ghazghkull Thraka"],
        "reading": [],
        "rivals": ["militarum", "astartes", "tau"],
    },
    {
        "slug": "tau",
        "name": "Imperio T'au",
        "side": "xenos",
        "color": "#7fb5d6",
        "tagline": "Una civilización joven que cree en el Bien Mayor.",
        "tone": "Optimista y tecnológico",
        "difficulty": 1,
        "summary": [
            "El Imperio T'au es una civilización joven que se expande por la galaxia en nombre del Bien Mayor (Tau'va): la idea de que todas las razas cooperen bajo el liderazgo de los T'au. Quien lo acepta es bienvenido; quien lo rechaza puede ser conquistado.",
            "Su sociedad está dividida en castas: Fuego (soldados), Agua (diplomáticos), Aire (pilotos), Tierra (artesanos) y los Etéreos, líderes casi venerados. Luchan con Trajes de Combate y aliados como los Kroot, y dependen de armas de disparo y tecnología.",
        ],
        "key_points": [
            "No usan la Disformidad: su tecnología es limpia y, sobre todo, a distancia.",
            "El Comandante Farsight se separó del resto y lidera sus propias Enclaves.",
            "Ofrecen una alternativa a la opresión imperial… si aceptas sus condiciones.",
        ],
        "characters": ["Comandante Farsight", "Shadowsun"],
        "reading": ["Fire Caste, de Peter Fehervari"],
        "rivals": ["astartes", "militarum", "orks", "tyranids"],
    },
    {
        "slug": "tyranids",
        "name": "Tiránidos",
        "side": "xenos",
        "color": "#d4526e",
        "tagline": "Una flota que devora galaxias enteras.",
        "tone": "Cósmico y aterrador",
        "difficulty": 2,
        "summary": [
            "Los Tiránidos consumen toda la biomasa de los mundos que invaden para crear más criaturas. Los gobierna la Mente Enjambre, una conciencia colectiva que dirige a innumerables organismos.",
            "Llegan desde fuera de la galaxia en Flotas Colmena como Behemoth, Kraken o Leviatán. Antes de cada invasión aparecen los Genestealers, infiltrados que preparan el terreno. No buscan política ni ideología: buscan comer.",
        ],
        "key_points": [
            "Todas las criaturas son biológicas y se adaptan a sus presas.",
            "Su llegada crea la Sombra en la Disformidad, que bloquea los poderes psíquicos.",
            "Son una amenaza para todas las razas por igual.",
        ],
        "characters": ["La Mente Enjambre", "Deathleaper"],
        "reading": [],
        "rivals": ["astartes", "militarum", "tau", "aeldari"],
    },
    {
        "slug": "necrons",
        "name": "Necrones",
        "side": "xenos",
        "color": "#3fe0b0",
        "tagline": "Reyes esqueleto que despiertan tras millones de años.",
        "tone": "Antiguo y melancólico",
        "difficulty": 2,
        "summary": [
            "Los Necrones fueron los Necrontyr, una raza mortal que temía a la muerte. Aceptaron un pacto con los C'tan, seres cósmicos de energía, y se transformaron en soldados de «metal vivo». Pero perdieron la identidad y luego se rebelaron contra sus falsos dioses.",
            "Tras millones de años dormidos en sus Mundos Tumba, despiertan por toda la galaxia para reclamar su antiguo imperio. Sus dinastías compiten entre sí, con Nobles y Overlords al frente. Su gran unificador es el Rey Silencioso, Szarekh, que ha regresado.",
        ],
        "key_points": [
            "Son casi indestructibles: se reparan y se levantan.",
            "Muchos Necrones aún no se han despertado.",
            "Su tecnología es tan avanzada que el Imperio no la entiende.",
        ],
        "characters": ["Szarekh, el Rey Silencioso", "Imotekh el Señor de la Tormenta"],
        "reading": ["The Infinite and the Divine, de Robert Rath"],
        "rivals": ["astartes", "mechanicus", "aeldari"],
    },
    {
        "slug": "votann",
        "name": "Liga de Votann",
        "side": "xenos",
        "color": "#b5651d",
        "tagline": "Mineros ancestrales que llevan a sus muertos consigo, en forma de datos.",
        "tone": "Robusto y pragmático",
        "difficulty": 1,
        "summary": [
            "La Liga de Votann es una de las razas xenos más recientes en aparecer en el imaginario de la galaxia: humanoides bajos y fornidos, herederos de una civilización minera muy anterior al propio Imperio, que quedaron aislados de sus primos Ogryn hace decenas de miles de años.",
            "Cada Liga guarda el conocimiento de sus antepasados en un Núcleo Ancestral, una suerte de inteligencia artificial que conserva la memoria y la personalidad de los muertos ilustres. Combaten con tecnología iónica y máquinas robustas, y comercian con casi cualquiera, Imperio incluido, siempre que el trato les convenga.",
        ],
        "key_points": [
            "Sus Núcleos Ancestrales conservan la memoria de generaciones enteras de antepasados.",
            "Se organizan en Ligas independientes, cada una con su propio Kâhl (líder).",
            "Comercian con casi todas las facciones, incluido el Imperio, cuando les resulta rentable.",
        ],
        "characters": [],
        "reading": [],
        "rivals": ["orks", "necrons"],
    },
]

TIMELINE = [
    {
        "title": "Un emperador reúne a la humanidad",
        "text": "Hace unos diez mil años, el Emperador, un ser inmortal con enormes poderes psíquicos, une la Tierra y lanza la Gran Cruzada para reunificar a la humanidad dispersa por la galaxia. Sus veinte hijos, los Primarcas, lideran los ejércitos.",
    },
    {
        "title": "La Herejía de Horus",
        "text": "Horus, el Primarca favorito del Emperador, cae bajo la influencia del Caos y arrastra a la mitad de las Legiones. La guerra civil culmina en el Asedio de Terra: Horus muere y el Emperador queda gravemente herido.",
    },
    {
        "title": "El Trono Dorado",
        "text": "El cuerpo del Emperador se mantiene en el Trono Dorado. Su presencia sostiene el Astronomicón, una luz psíquica sin la que las naves no podrían navegar por la Disformidad. Cada día se sacrifica un millar de almas para mantenerlo.",
    },
    {
        "title": "Diez mil años de guerra",
        "text": "El Imperio sobrevive como una teocracia militar, burocrática y opresiva. Los xenos acechan desde todas partes y el Caos crece en las sombras.",
    },
    {
        "title": "El final del milenio 41",
        "text": "Abaddon lanza la 13.ª Cruzada Negra, Cadia cae y se abre la Gran Grieta (Cicatrix Maledictum), que divide la galaxia. Roboute Guilliman despierta tras diez mil años y toma las riendas del Imperio.",
    },
]

GLOSSARY = [
    ("Disformidad (Warp)", "Dimensión de energía y emociones desde la que actúan los dioses del Caos. Permite viajar más rápido que la luz, pero es peligrosa."),
    ("Primarca", "Uno de los veinte hijos genéticos del Emperador. Cada Legión de Marines Espaciales tenía el suyo."),
    ("Xenos", "Cualquier raza no humana."),
    ("Herejía", "En el Imperio, cualquier creencia que contradiga la doctrina oficial. Se castiga con la muerte."),
    ("Bólter", "El arma de proyectiles explosivos de los Marines Espaciales."),
    ("Mundo Colmena", "Un planeta cubierto de ciudades gigantescas, con miles de millones de habitantes."),
    ("Psíquico", "Persona con poderes mentales. Útil, peligrosa y siempre vigilada."),
]

TASTES = [
    ("Quiero superhumanos con armadura y honor", "astartes"),
    ("Prefiero soldados corrientes contra el universo", "militarum"),
    ("Me atrae la tecnología como religión", "mechanicus"),
    ("Quiero humor negro y caos", "orks"),
    ("Busco tragedia y elegancia", "aeldari"),
    ("Me gusta el terror cósmico", "tyranids"),
    ("Prefiero algo antiguo y melancólico", "necrons"),
    ("Quiero ser el villano", "chaos-marines"),
    ("Quiero secretos y una orden con un pasado oscuro", "dark-angels"),
    ("Busco intriga, dobles lealtades y ningún nombre real", "alpha-legion"),
    ("Quiero enanos-cíborg pragmáticos con tecnología ancestral", "votann"),
]
